
package org.superklamer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalog", targetNamespace = "http://superklamer.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalog {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://superklamer.org/", className = "org.superklamer.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://superklamer.org/", className = "org.superklamer.GetProductCategoriesResponse")
    @Action(input = "http://superklamer.org/ProductCatalog/getProductCategoriesRequest", output = "http://superklamer.org/ProductCatalog/getProductCategoriesResponse")
    public List<String> getProductCategories();

}
